import React, { createContext, useState, useContext } from 'react';
import type { ReactNode } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    'nav.home': 'Beranda',
    'nav.about': 'Tentang Kami',
    'nav.alumni': 'Daftar Alumni',
    'nav.jobs': 'Loker',
    'nav.news': 'Berita',
    'nav.contact': 'Hubungi Kami',
    'nav.document': 'Perpanjang Dokumen',
    'lang.id': 'Indonesia (ID)',
    'lang.en': 'Inggris (EN)',
    'bahasa': 'Bahasa',
    'home.hero.badge': 'Portal Resmi Ikatan Alumni Aman Jaya',
    'home.hero.default_headline': 'Sinergi Alumni untuk Almamater dan Bangsa',
    'home.hero.default_subheadline': 'Selamat datang di portal resmi Ikatan Alumni Aman Jaya. Wadah kolaborasi, berbagi inspirasi, dan mempererat tali persaudaraan antar alumni.',
    'home.hero.btn_directory': 'Jelajahi Direktori Alumni',
    'home.hero.btn_learn': 'Pelajari Lebih Lanjut',
    'home.about.title': 'Tentang IAAJ',
    'home.about.desc': 'Ikatan Alumni didirikan untuk menjembatani alumni dalam berbagai sektor industri, membangun jejaring yang kokoh, dan memberikan kontribusi positif bagi almamater serta masyarakat luas.',
    'home.about.btn': 'Pelajari Selengkapnya',
    'home.jobs.title': 'Peluang Karir & Loker',
    'home.jobs.desc': 'Temukan berbagai peluang karir eksklusif dari jaringan korporat alumni kami. Mari bersama-sama membangun ekosistem profesional yang saling mendukung dan membuka jalan sukses.',
    'home.jobs.btn': 'Lihat Lowongan Kerja',
    'home.alumni.title': 'Direktori Alumni Berprestasi',
    'home.alumni.desc': 'Terhubung kembali dengan sahabat satu almamater yang kini berkarya di berbagai sektor strategis tanah air dan internasional.',
    'home.alumni.btn': 'Menuju Daftar Alumni',
    'home.news.subtitle': 'Publikasi & Kegiatan',
    'home.news.title': 'Buletin Alumni',
    'home.news.btn_all': 'Lihat Semua Berita',
    'home.news.badge': 'Berita',
    'home.news.by': 'Oleh:',
    'home.news.read_article': 'Baca Artikel',
    'home.news.empty': 'Belum ada berita terbaru.',
    'home.news.read': 'Baca',
    'home.cta.title': 'Ingin Membagikan Lowongan Kerja atau Cerita Sukses Anda?',
    'home.cta.desc': 'Hubungi sekretariat pengurus IAAJ atau gunakan portal anggota untuk mempublikasikan loker dan artikel inspiratif bagi sesama alumni.',
    'home.cta.btn_contact': 'Kirim Pesan ke Pengurus',
    'home.cta.btn_career': 'Lihat Portal Karir',
    'footer.brand.desc': 'Portal resmi Ikatan Alumni Aman Jaya. Wadah kolaborasi, berbagi inspirasi, dan mempererat tali persaudaraan antar alumni.',
    'footer.links.title': 'Tautan Cepat',
    'footer.programs.title': 'Program Studi',
    'footer.contact.title': 'Contact',
    'about.hero.badge': 'Profil Organisasi',
    'about.hero.title': 'Tentang Ikatan Alumni Aman Jaya',
    'about.hero.desc': 'Selamat datang di halaman Tentang Kami. Ikatan Alumni (IAAJ) adalah wadah resmi yang menghubungkan seluruh lulusan dalam semangat kebersamaan dan kontribusi positif.',
    'about.history.badge': 'Kilas Balik',
    'about.history.title': 'Warisan Kebersamaan yang Terus Berkembang',
    'about.history.p1': 'Didirikan pada tahun 1985, Ikatan Alumni Aman Jaya (IAAJ) berawal dari inisiatif para wisudawan angkatan pertama yang berkomitmen untuk terus menjaga tali silaturahmi dengan kampus.',
    'about.history.p2': 'Kini, lebih dari empat dekade kemudian, IAAJ telah berkembang menjadi organisasi alumni modern yang menaungi lebih dari 45.000 anggota yang tersebar di 38 provinsi di Indonesia dan lebih dari 20 negara di dunia.',
    'about.history.btn': 'Lihat Direktori Alumni Kami',
    'about.history.img_cap': 'Keluarga besar IAAJ dalam Temu Alumni Nasional di Jakarta Convention Center.',
    'about.vision.title': 'Visi Kami',
    'about.vision.desc': 'Menjadi wadah ikatan alumni yang mandiri, berintegritas tinggi, unggul secara global, dan senantiasa menjadi penggerak perubahan positif bagi almamater, masyarakat, dan bangsa.',
    'about.mission.title': 'Misi Kami',
    'about.mission.li1': 'Membangun ekosistem networking yang inklusif, kolaboratif, dan profesional.',
    'about.mission.li2': 'Mendukung kemajuan riset, inovasi, dan akreditasi internasional almamater.',
    'about.mission.li3': 'Menyalurkan beasiswa dan bimbingan karir bagi generasi muda mahasiswa.',
    'about.board.badge': 'Kepengurusan',
    'about.board.title': 'Dewan Pengurus',
    'about.board.desc': 'Membimbing organisasi menuju era transformasi digital dan sinergi alumni yang berkelanjutan.',
    'about.board.period': 'Masa Bakti',
    'about.board.empty': 'Belum ada data pengurus yang ditambahkan.',
    'contact.hero.badge': 'Layanan & Aspirasi',
    'contact.hero.title': 'Hubungi Sekretariat IAAJ',
    'contact.hero.desc': 'Kami siap melayani kebutuhan informasi keanggotaan, kemitraan karir, serta menerima aspirasi seluruh alumni Universitas Aman Jaya.',
    'contact.alumni.badge': 'Formulir Pendaftaran Alumni Baru',
    'contact.alumni.desc': 'Daftarkan diri Anda untuk dimasukkan ke dalam direktori alumni resmi IAAJ.',
    'contact.alumni.success': 'Pendaftaran Berhasil!',
    'contact.alumni.success_desc': 'Terima kasih, data Anda telah disimpan dan akan segera muncul di Direktori Alumni.',
    'contact.alumni.btn': 'Daftar Sekarang',
    'contact.alumni.loading': 'Mengirim...',
    'contact.doc.badge': 'Formulir Perpanjang Dokumen',
    'contact.doc.desc': 'Ajukan permohonan perpanjangan dokumen Anda dengan mengisi formulir di bawah ini.',
    'contact.doc.success': 'Permohonan Berhasil Dikirim!',
    'contact.doc.success_desc': 'Terima kasih, permohonan perpanjangan dokumen Anda akan segera diproses oleh tim kami.',
    'contact.doc.btn': 'Kirim Permohonan',
    'contact.message.title': 'Kirim Pesan atau Aspirasi',
    'contact.message.desc': 'Isi formulir di bawah ini, tim sekretariat kami akan merespons dalam waktu 1x24 jam kerja.',
    'contact.message.success': 'Pesan Berhasil Terkirim!',
    'contact.message.success_desc': 'Terima kasih telah menghubungi kami. Pesan Anda telah diteruskan ke divisi terkait.',
    'contact.message.btn': 'Kirimkan Pesan Sekarang',
    'contact.info.title': 'Request a Call Back',
    'contact.info.address': 'Alamat Kantor Pusat:',
    'contact.info.hours': 'Jam Layanan:',
    'contact.info.hours_desc': 'Senin - Jumat: 08.30 - 17.00 WIB',
    'contact.info.closed': 'Sabtu, Minggu & Hari Libur Nasional Tutup',
    'contact.info.phone': 'Telepon & Hotline:',
    'contact.info.email': 'Email Resmi:',
    'contact.faq.title': 'Pertanyaan Populer',
    'alumni.hero.badge': 'Database Keanggotaan Alumni',
    'alumni.hero.title': 'Direktori Alumni Aman Jaya',
    'alumni.hero.desc': 'Temukan dan terhubung kembali dengan para lulusan Ikatan Alumni Aman Jaya (IAAJ) lintas angkatan, bidang keahlian maritim, serta kepelabuhanan global.',
    'alumni.search.placeholder': 'Cari nama alumni, angkatan, instansi...',
    'alumni.filter.all_prodi': 'Semua Program Studi',
    'alumni.filter.all_batch': 'Semua Angkatan',
    'alumni.filter.btn': 'Form Daftar Alumni',
    'alumni.table.title': 'Tabel Data Alumni',
    'alumni.table.no_data': 'Data Alumni Tidak Ditemukan',
    'alumni.table.no_data_desc': 'Tidak ada data yang sesuai dengan pencarian atau filter yang dipilih. Silakan sesuaikan filter Program Studi atau Angkatan.',
    'alumni.table.reset': 'Reset Filter',
    'alumni.table.col.no': 'No.',
    'alumni.table.col.name': 'Nama',
    'alumni.table.col.prodi': 'Program Studi',
    'alumni.table.col.batch': 'Angkatan ke-',
    'alumni.table.col.action': 'Aksi',
    'alumni.table.detail': 'Detail',
    'alumni.modal.role': 'Jabatan / Profesi:',
    'alumni.modal.location': 'Domisili / Wilayah Tugas:',
    'alumni.modal.notes': 'Catatan & Pengalaman:',
    'alumni.modal.email': 'Kirim Email',
    'alumni.modal.no_email': 'Kontak email belum dicantumkan',
    'jobs.hero.badge': 'Pusat Karir & Kerjasama Industri',
    'jobs.hero.title': 'Peluang Karir & Lowongan Kerja Alumni',
    'jobs.hero.desc': 'Temukan peluang karir terbaik dari jaringan mitra perusahaan IAAJ. Dapatkan informasi lowongan pekerjaan terkini yang relevan dengan keahlian dan pengalaman Anda.',
    'jobs.search.placeholder': 'Cari posisi, kata kunci, perusahaan...',
    'jobs.filter.all_type': 'Semua Tipe',
    'jobs.card.detail': 'Detail',
    'jobs.card.apply': 'Lamar Posisi',
    'jobs.modal.salary': 'Estimasi Gaji:',
    'jobs.modal.deadline': 'Batas Lamaran:',
    'jobs.modal.desc': 'Deskripsi Pekerjaan',
    'jobs.modal.req': 'Persyaratan & Kualifikasi',
    'jobs.modal.close': 'Tutup',
    'jobs.modal.apply': 'Lamar Sekarang',
    'jobs.apply.title': 'Lamar Pekerjaan',
    'jobs.apply.success': 'Lamaran Terkirim!',
    'jobs.apply.success_desc': 'Tim HR perusahaan akan meninjau berkas lamaran Anda.',
    'jobs.apply.name': 'Nama Lengkap *',
    'jobs.apply.email': 'Email *',
    'jobs.apply.phone': 'No. WhatsApp *',
    'jobs.apply.cv': 'Tautan Resume / CV (Google Drive / LinkedIn) *',
    'jobs.apply.note': 'Pesan Pengantar / Cover Note',
    'jobs.apply.cancel': 'Batal',
    'jobs.apply.submit': 'Kirim Lamaran',
    'news.hero.badge': 'Informasi & Publikasi',
    'news.hero.title': 'Kabar & Berita Alumni Aman Jaya',
    'news.hero.desc': 'Ikuti perkembangan almamater, liputan agenda reuni akbar, dan capaian inspiratif alumni di berbagai belahan dunia.',
    'news.search.placeholder': 'Cari berita atau pengumuman...',
    'news.highlight.badge': 'Sorotan Utama',
    'news.highlight.news': 'Berita',
    'news.highlight.author': 'Oleh:',
    'news.highlight.read_more': 'Baca Selengkapnya',
    'news.list.title_all': 'Berita Terkini',
    'news.list.title_cat': 'Berita Kategori:',
    'news.list.total': '{count} artikel',
    'news.list.loading': 'Memuat...',
    'news.list.no_data': 'Berita Tidak Ditemukan',
    'news.list.no_data_desc': 'Coba gunakan kata kunci pencarian yang lain.',
    'news.card.news': 'Berita',
    'news.card.read': 'Baca',
    'news.bulletin.title': 'Buletin IAAJ',
    'news.bulletin.total': '{count} buletin',
    'news.bulletin.no_data': 'Belum Ada Buletin',
    'news.bulletin.no_data_desc': 'Buletin resmi IAAJ akan segera dipublikasikan di sini.',
    'news.bulletin.badge': 'Buletin',
    'news.bulletin.detail': 'Lihat Detail',
    'news_detail.not_found': 'Berita tidak ditemukan',
    'news_detail.back_btn': 'Kembali ke Berita',
    'news_detail.breadcrumb.home': 'Beranda',
    'news_detail.breadcrumb.news': 'Kabar Alumni',
    'news_detail.type.bulletin': 'Buletin',
    'news_detail.type.news': 'Berita Utama',
    'news_detail.category': 'Kategori:',
    'news_detail.share.title': 'Bagikan Kabar Ini:',
    'news_detail.share.copy': 'Salin Tautan',
    'news_detail.share.copied': 'Tersalin!',
    'news_detail.related.title': 'Kabar Terkait Lainnya',
    'news_detail.callout.title': 'Punya Berita atau Liputan Kegiatan?',
    'news_detail.callout.desc': 'Kirimkan naskah berita, rilis kegiatan temu alumni, atau pengumuman penting ke tim redaksi Humas IAAJ.',
    'news_detail.callout.btn': 'Hubungi Tim Redaksi',
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.alumni': 'Alumni Directory',
    'nav.jobs': 'Jobs',
    'nav.news': 'News',
    'nav.contact': 'Contact Us',
    'nav.document': 'Document Extension',
    'lang.id': 'Indonesian (ID)',
    'lang.en': 'English (EN)',
    'bahasa': 'Language',
    'home.hero.badge': 'Official Portal of Aman Jaya Alumni Association',
    'home.hero.default_headline': 'Alumni Synergy for Alma Mater and Nation',
    'home.hero.default_subheadline': 'Welcome to the official portal of the Aman Jaya Alumni Association. A space to collaborate, share inspiration, and strengthen ties between alumni.',
    'home.hero.btn_directory': 'Explore Alumni Directory',
    'home.hero.btn_learn': 'Learn More',
    'home.about.title': 'About IAAJ',
    'home.about.desc': 'The Alumni Association was founded to bridge alumni across various industrial sectors, build strong networks, and make positive contributions to the alma mater and society.',
    'home.about.btn': 'Learn More',
    'home.jobs.title': 'Career Opportunities & Jobs',
    'home.jobs.desc': 'Discover exclusive career opportunities from our corporate alumni network. Let\'s build a mutually supportive professional ecosystem and pave the way to success.',
    'home.jobs.btn': 'View Job Openings',
    'home.alumni.title': 'Outstanding Alumni Directory',
    'home.alumni.desc': 'Reconnect with your alma mater friends who are now working in various strategic sectors both nationally and internationally.',
    'home.alumni.btn': 'Go to Alumni List',
    'home.news.subtitle': 'Publications & Activities',
    'home.news.title': 'Alumni Bulletin',
    'home.news.btn_all': 'View All News',
    'home.news.badge': 'News',
    'home.news.by': 'By:',
    'home.news.read_article': 'Read Article',
    'home.news.empty': 'No latest news yet.',
    'home.news.read': 'Read',
    'home.cta.title': 'Want to Share Job Openings or Your Success Story?',
    'home.cta.desc': 'Contact the IAAJ secretariat or use the member portal to publish job vacancies and inspiring articles for fellow alumni.',
    'home.cta.btn_contact': 'Send Message to Board',
    'home.cta.btn_career': 'View Career Portal',
    'footer.brand.desc': 'Official portal of Aman Jaya Alumni Association. A space to collaborate, share inspiration, and strengthen ties between alumni.',
    'footer.links.title': 'Quick Links',
    'footer.programs.title': 'Study Programs',
    'footer.contact.title': 'Contact',
    'about.hero.badge': 'Organization Profile',
    'about.hero.title': 'About Aman Jaya Alumni Association',
    'about.hero.desc': 'Welcome to the About Us page. The Alumni Association (IAAJ) is the official platform connecting all graduates in a spirit of togetherness and positive contribution.',
    'about.history.badge': 'Flashback',
    'about.history.title': 'A Growing Legacy of Togetherness',
    'about.history.p1': 'Founded in 1985, the Aman Jaya Alumni Association (IAAJ) began with the initiative of the first batch of graduates who were committed to maintaining ties with the campus.',
    'about.history.p2': 'Now, more than four decades later, IAAJ has grown into a modern alumni organization with over 45,000 members spread across 38 provinces in Indonesia and more than 20 countries worldwide.',
    'about.history.btn': 'View Our Alumni Directory',
    'about.history.img_cap': 'The IAAJ extended family at the National Alumni Gathering in the Jakarta Convention Center.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To become an independent alumni association with high integrity, global excellence, and constantly driving positive change for the alma mater, society, and the nation.',
    'about.mission.title': 'Our Mission',
    'about.mission.li1': 'Build an inclusive, collaborative, and professional networking ecosystem.',
    'about.mission.li2': 'Support the advancement of research, innovation, and international accreditation of the alma mater.',
    'about.mission.li3': 'Provide scholarships and career guidance for young students.',
    'about.board.badge': 'Management',
    'about.board.title': 'Board of Directors',
    'about.board.desc': 'Guiding the organization towards an era of digital transformation and sustainable alumni synergy.',
    'about.board.period': 'Term of Office',
    'about.board.empty': 'No management data added yet.',
    'contact.hero.badge': 'Service & Aspirations',
    'contact.hero.title': 'Contact IAAJ Secretariat',
    'contact.hero.desc': 'We are ready to serve information needs, career partnerships, and receive aspirations from all Aman Jaya University alumni.',
    'contact.alumni.badge': 'New Alumni Registration Form',
    'contact.alumni.desc': 'Register yourself to be included in the official IAAJ alumni directory.',
    'contact.alumni.success': 'Registration Successful!',
    'contact.alumni.success_desc': 'Thank you, your data has been saved and will soon appear in the Alumni Directory.',
    'contact.alumni.btn': 'Register Now',
    'contact.alumni.loading': 'Sending...',
    'contact.doc.badge': 'Document Extension Form',
    'contact.doc.desc': 'Apply for your document extension by filling out the form below.',
    'contact.doc.success': 'Request Sent Successfully!',
    'contact.doc.success_desc': 'Thank you, your document extension request will be processed soon by our team.',
    'contact.doc.btn': 'Submit Request',
    'contact.message.title': 'Send Message or Aspiration',
    'contact.message.desc': 'Fill out the form below, our secretariat team will respond within 1x24 working hours.',
    'contact.message.success': 'Message Sent Successfully!',
    'contact.message.success_desc': 'Thank you for contacting us. Your message has been forwarded to the relevant division.',
    'contact.message.btn': 'Send Message Now',
    'contact.info.title': 'Request a Call Back',
    'contact.info.address': 'Head Office Address:',
    'contact.info.hours': 'Service Hours:',
    'contact.info.hours_desc': 'Monday - Friday: 08.30 - 17.00 WIB',
    'contact.info.closed': 'Closed on Saturdays, Sundays & National Holidays',
    'contact.info.phone': 'Phone & Hotline:',
    'contact.info.email': 'Official Email:',
    'contact.faq.title': 'Popular Questions',
    'alumni.hero.badge': 'Alumni Membership Database',
    'alumni.hero.title': 'Aman Jaya Alumni Directory',
    'alumni.hero.desc': 'Find and reconnect with Aman Jaya Alumni Association (IAAJ) graduates across batches, maritime expertise fields, and global ports.',
    'alumni.search.placeholder': 'Search alumni name, batch, institution...',
    'alumni.filter.all_prodi': 'All Study Programs',
    'alumni.filter.all_batch': 'All Batches',
    'alumni.filter.btn': 'Alumni Registration Form',
    'alumni.table.title': 'Alumni Data Table',
    'alumni.table.no_data': 'Alumni Data Not Found',
    'alumni.table.no_data_desc': 'No data matches the search or selected filters. Please adjust the Study Program or Batch filters.',
    'alumni.table.reset': 'Reset Filters',
    'alumni.table.col.no': 'No.',
    'alumni.table.col.name': 'Name',
    'alumni.table.col.prodi': 'Study Program',
    'alumni.table.col.batch': 'Batch',
    'alumni.table.col.action': 'Action',
    'alumni.table.detail': 'Detail',
    'alumni.modal.role': 'Position / Profession:',
    'alumni.modal.location': 'Domicile / Duty Area:',
    'alumni.modal.notes': 'Notes & Experience:',
    'alumni.modal.email': 'Send Email',
    'alumni.modal.no_email': 'Email contact not listed',
    'jobs.hero.badge': 'Career Center & Industry Collaboration',
    'jobs.hero.title': 'Career Opportunities & Alumni Job Vacancies',
    'jobs.hero.desc': 'Find the best career opportunities from the IAAJ company partner network. Get the latest job vacancy information relevant to your skills and experience.',
    'jobs.search.placeholder': 'Search positions, keywords, companies...',
    'jobs.filter.all_type': 'All Types',
    'jobs.card.detail': 'Detail',
    'jobs.card.apply': 'Apply Position',
    'jobs.modal.salary': 'Estimated Salary:',
    'jobs.modal.deadline': 'Application Deadline:',
    'jobs.modal.desc': 'Job Description',
    'jobs.modal.req': 'Requirements & Qualifications',
    'jobs.modal.close': 'Close',
    'jobs.modal.apply': 'Apply Now',
    'jobs.apply.title': 'Apply for Job',
    'jobs.apply.success': 'Application Sent!',
    'jobs.apply.success_desc': 'The company HR team will review your application file.',
    'jobs.apply.name': 'Full Name *',
    'jobs.apply.email': 'Email *',
    'jobs.apply.phone': 'WhatsApp No. *',
    'jobs.apply.cv': 'Resume / CV Link (Google Drive / LinkedIn) *',
    'jobs.apply.note': 'Introductory Message / Cover Note',
    'jobs.apply.cancel': 'Cancel',
    'jobs.apply.submit': 'Submit Application',
    'news.hero.badge': 'Information & Publication',
    'news.hero.title': 'News & Updates of Aman Jaya Alumni',
    'news.hero.desc': 'Follow alma mater developments, grand reunion agenda coverage, and inspiring alumni achievements worldwide.',
    'news.search.placeholder': 'Search news or announcements...',
    'news.highlight.badge': 'Main Highlight',
    'news.highlight.news': 'News',
    'news.highlight.author': 'By:',
    'news.highlight.read_more': 'Read More',
    'news.list.title_all': 'Latest News',
    'news.list.title_cat': 'News Category:',
    'news.list.total': '{count} articles',
    'news.list.loading': 'Loading...',
    'news.list.no_data': 'News Not Found',
    'news.list.no_data_desc': 'Try using different search keywords.',
    'news.card.news': 'News',
    'news.card.read': 'Read',
    'news.bulletin.title': 'IAAJ Bulletin',
    'news.bulletin.total': '{count} bulletins',
    'news.bulletin.no_data': 'No Bulletins Yet',
    'news.bulletin.no_data_desc': 'Official IAAJ bulletins will be published here soon.',
    'news.bulletin.badge': 'Bulletin',
    'news.bulletin.detail': 'View Detail',
    'news_detail.not_found': 'News not found',
    'news_detail.back_btn': 'Back to News',
    'news_detail.breadcrumb.home': 'Home',
    'news_detail.breadcrumb.news': 'Alumni News',
    'news_detail.type.bulletin': 'Bulletin',
    'news_detail.type.news': 'Main News',
    'news_detail.category': 'Category:',
    'news_detail.share.title': 'Share this News:',
    'news_detail.share.copy': 'Copy Link',
    'news_detail.share.copied': 'Copied!',
    'news_detail.related.title': 'Other Related News',
    'news_detail.callout.title': 'Have News or Event Coverage?',
    'news_detail.callout.desc': 'Send news manuscripts, alumni gathering event releases, or important announcements to the IAAJ PR editorial team.',
    'news_detail.callout.btn': 'Contact Editorial Team',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('id');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
